"""empty message

Revision ID: 7dd497935d92
Revises: e41387200ed7
Create Date: 2021-04-15 10:09:11.750835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd497935d92'
down_revision = 'e41387200ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.add_column('shows', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('venue_image_link', sa.String(length=500), nullable=True))
    op.add_column('shows', sa.Column('venue_name', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Update the Shows data to include this info:
    op.execute("UPDATE shows \
                SET artist_name = 'Guns N Petals'\
                WHERE artist_id = (SELECT artists.id from artists where artists.name='Guns N Petals');")

    op.execute("UPDATE shows \
                SET artist_image_link = (SELECT artists.image_link from artists where artists.name='Guns N Petals')\
                WHERE artist_id = (SELECT artists.id from artists where artists.name='Guns N Petals');")

    op.execute("UPDATE shows \
                SET artist_name = 'Matt Quevedo'\
                WHERE artist_id = (SELECT artists.id from artists where artists.name='Matt Quevedo');")

    op.execute("UPDATE shows \
                SET artist_image_link = (SELECT artists.image_link from artists where artists.name='Matt Quevedo')\
                WHERE artist_id = (SELECT artists.id from artists where artists.name='Matt Quevedo');")

    op.execute("UPDATE shows \
                SET artist_name = 'The Wild Sax Band'\
                WHERE artist_id = (SELECT artists.id from artists where artists.name='The Wild Sax Band');")

    op.execute("UPDATE shows \
                SET artist_image_link = (SELECT artists.image_link from artists where artists.name='The Wild Sax Band')\
                WHERE artist_id = (SELECT artists.id from artists where artists.name='The Wild Sax Band');")

    op.execute("UPDATE shows \
                SET venue_name = 'The Musical Hop'\
                WHERE venue_id = (SELECT venues.id from venues where venues.name='The Musical Hop');")

    op.execute("UPDATE shows \
                SET venue_image_link = (SELECT venues.image_link from venues where venues.name='The Musical Hop')\
                WHERE venue_id = (SELECT venues.id from venues where venues.name='The Musical Hop');")

    op.execute("UPDATE shows \
                SET venue_name = 'The Dueling Pianos Bar'\
                WHERE venue_id = (SELECT venues.id from venues where venues.name='The Dueling Pianos Bar');")

    op.execute("UPDATE shows \
                SET venue_image_link = (SELECT venues.image_link from venues where venues.name='The Dueling Pianos Bar')\
                WHERE venue_id = (SELECT venues.id from venues where venues.name='The Dueling Pianos Bar');")

    op.execute("UPDATE shows \
                   SET venue_name = 'Park Square Live Music & Coffee'\
                   WHERE venue_id = (SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee');")

    op.execute("UPDATE shows \
                   SET venue_image_link = (SELECT venues.image_link from venues where venues.name='Park Square Live Music & Coffee')\
                   WHERE venue_id = (SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee');")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'venue_image_link')
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'artist_image_link')
    # ### end Alembic commands ###
