"""empty message

Revision ID: e41387200ed7
Revises: 
Create Date: 2021-04-12 16:38:34.882416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41387200ed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=False),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.Column('looking_for_talent', sa.Boolean(), nullable=False),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_genre_items',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_genre_items',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id')
    )
    # ### end Alembic commands ###

    # Upgrade commands used to populate initial information
    # Populate Genres table
    op.execute("INSERT INTO genres (name) VALUES ('Alternative');")
    op.execute("INSERT INTO genres (name) VALUES ('Blues');")
    op.execute("INSERT INTO genres (name) VALUES ('Classical');")
    op.execute("INSERT INTO genres (name) VALUES ('Country');")
    op.execute("INSERT INTO genres (name) VALUES ('Electronic');")
    op.execute("INSERT INTO genres (name) VALUES ('Folk');")
    op.execute("INSERT INTO genres (name) VALUES ('Funk');")
    op.execute("INSERT INTO genres (name) VALUES ('Hip-Hop');")
    op.execute("INSERT INTO genres (name) VALUES ('Heavy Metal');")
    op.execute("INSERT INTO genres (name) VALUES ('Instrumental');")
    op.execute("INSERT INTO genres (name) VALUES ('Jazz');")
    op.execute("INSERT INTO genres (name) VALUES ('Musical Theatre');")
    op.execute("INSERT INTO genres (name) VALUES ('Pop');")
    op.execute("INSERT INTO genres (name) VALUES ('Punk');")
    op.execute("INSERT INTO genres (name) VALUES ('R&B');")
    op.execute("INSERT INTO genres (name) VALUES ('Reggae');")
    op.execute("INSERT INTO genres (name) VALUES ('Rock n Roll');")
    op.execute("INSERT INTO genres (name) VALUES ('Soul');")
    op.execute("INSERT INTO genres (name) VALUES ('Swing');")
    op.execute("INSERT INTO genres (name) VALUES ('Other');")

    # Populate artist table.
    op.execute("INSERT INTO artists (name, \
                                     city, \
                                     state, \
                                     phone, \
                                     facebook_link, \
                                     image_link, \
                                     website_link, \
                                     seeking_venue, \
                                     seeking_description) \
                                VALUES ('Guns N Petals', \
                                        'San Francisco', \
                                        'CA', \
                                        '326-123-5000',\
                                        'https://www.facebook.com/GunsNPetals',\
                                        'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80',\
                                        'https://www.gunsnpetalsband.com', \
                                        TRUE, \
                                        'Looking for shows to perform at in the San Francisco Bay Area!');")

    op.execute("INSERT INTO artists (name, \
                                     city, \
                                     state, \
                                     phone, \
                                     facebook_link, \
                                     image_link, \
                                     seeking_venue) \
                             VALUES ('Matt Quevedo', \
                                     'New York', \
                                     'NY', \
                                     '300-400-5000',\
                                     'https://www.facebook.com/mattquevedo923251523',\
                                     'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80',\
                                      FALSE);")

    op.execute("INSERT INTO artists (name, \
                                     city, \
                                     state, \
                                     phone, \
                                     image_link, \
                                     seeking_venue) \
                             VALUES ('The Wild Sax Band', \
                                     'San Francisco', \
                                     'CA', \
                                     '432-325-5432',\
                                     'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80',\
                                      FALSE);")

    # Populate venue table.
    op.execute("INSERT INTO venues (name, \
                                    city, \
                                    state, \
                                    phone, \
                                    facebook_link, \
                                    image_link, \
                                    website_link, \
                                    looking_for_talent, \
                                    seeking_description) \
                            VALUES ('The Musical Hop', \
                                    'San Francisco', \
                                    'CA', \
                                    '123-123-1234',\
                                    'https://www.facebook.com/TheMusicalHop',\
                                    'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',\
                                    'https://www.themusicalhop.com', \
                                    TRUE, \
                                    'We are on the lookout for a local artist to play every two weeks. Please call us.');")

    op.execute("INSERT INTO venues (name, \
                                    address, \
                                    city, \
                                    state, \
                                    phone, \
                                    facebook_link, \
                                    image_link, \
                                    website_link, \
                                    looking_for_talent) \
                              VALUES ('The Dueling Pianos Bar', \
                                      '335 Delancey Street',\
                                      'New York', \
                                      'NY', \
                                      '914-003-1132',\
                                      'https://www.facebook.com/theduelingpianos',\
                                      'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80',\
                                      'https://www.theduelingpianos.com', \
                                      FALSE);")

    op.execute("INSERT INTO venues (name, \
                                    address, \
                                    city, \
                                    state, \
                                    phone, \
                                    facebook_link, \
                                    image_link, \
                                    website_link, \
                                    looking_for_talent) \
                              VALUES ('Park Square Live Music & Coffee', \
                                      '34 Whiskey Moore Ave',\
                                      'San Francisco', \
                                      'CA', \
                                      '415-000-1234',\
                                      'https://www.facebook.com/ParkSquareLiveMusicAndCoffee',\
                                      'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80',\
                                      'https://www.parksquarelivemusicandcoffee.com', \
                                      FALSE);")

    # Populate genre_to_artist table.
    op.execute("INSERT INTO artist_genre_items (genre_id, artist_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Rock n Roll'), \
                (SELECT artists.id from artists where artists.name='Guns N Petals'));")

    op.execute("INSERT INTO artist_genre_items (genre_id, artist_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Jazz'), \
                (SELECT artists.id from artists where artists.name='Matt Quevedo'));")

    op.execute("INSERT INTO artist_genre_items (genre_id, artist_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Jazz'), \
                (SELECT artists.id from artists where artists.name='The Wild Sax Band'));")

    op.execute("INSERT INTO artist_genre_items (genre_id, artist_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Classical'), \
                (SELECT artists.id from artists where artists.name='The Wild Sax Band'));")

    # Populate genre_to_venue table.
    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Jazz'), \
                (SELECT venues.id from venues where venues.name='The Musical Hop'));")


    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Reggae'), \
                (SELECT venues.id from venues where venues.name='The Musical Hop'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Swing'), \
                (SELECT venues.id from venues where venues.name='The Musical Hop'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Classical'), \
                (SELECT venues.id from venues where venues.name='The Musical Hop'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Folk'), \
                (SELECT venues.id from venues where venues.name='The Musical Hop'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Classical'), \
                (SELECT venues.id from venues where venues.name='The Dueling Pianos Bar'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='R&B'), \
                (SELECT venues.id from venues where venues.name='The Dueling Pianos Bar'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Hip-Hop'), \
                (SELECT venues.id from venues where venues.name='The Dueling Pianos Bar'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Rock n Roll'), \
                (SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Jazz'), \
                (SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Classical'), \
                (SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee'));")

    op.execute("INSERT INTO venue_genre_items (genre_id, venue_id) \
                VALUES\
                ((SELECT genres.id from genres where genres.name='Folk'), \
                (SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee'));")

    # Populate show table.
    op.execute("INSERT INTO shows (venue_id, \
                                   artist_id, \
                                   start_time) \
                            VALUES \
                                  ((SELECT venues.id from venues where venues.name='The Musical Hop'), \
                                   (SELECT artists.id from artists where artists.name='Guns N Petals'),\
                                   '2019-05-21T21:30:00.000Z');")

    op.execute("INSERT INTO shows (venue_id, \
                                   artist_id, \
                                   start_time) \
                            VALUES \
                                    ((SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee'), \
                                    (SELECT artists.id from artists where artists.name='Matt Quevedo'),\
                                    '2019-06-15T23:00:00.000Z');")

    op.execute("INSERT INTO shows (venue_id, \
                                   artist_id, \
                                   start_time) \
                            VALUES \
                                   ((SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee'), \
                                   (SELECT artists.id from artists where artists.name='The Wild Sax Band'),\
                                   '2035-04-01T20:00:00.000Z');")

    op.execute("INSERT INTO shows (venue_id, \
                                   artist_id, \
                                   start_time) \
                             VALUES \
                                   ((SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee'), \
                                   (SELECT artists.id from artists where artists.name='The Wild Sax Band'),\
                                   '2035-04-08T20:00:00.000Z');")

    op.execute("INSERT INTO shows (venue_id, \
                                   artist_id, \
                                   start_time) \
                            VALUES \
                                   ((SELECT venues.id from venues where venues.name='Park Square Live Music & Coffee'), \
                                   (SELECT artists.id from artists where artists.name='The Wild Sax Band'),\
                                   '2035-04-15T20:00:00.000Z');")

    op.execute("INSERT INTO shows (venue_id, \
                                   artist_id, \
                                   start_time) \
                            VALUES \
                                   ((SELECT venues.id from venues where venues.name='The Dueling Pianos Bar'), \
                                   (SELECT artists.id from artists where artists.name='Matt Quevedo'),\
                                   '2019-04-15T20:00:00.000Z');")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genre_items')
    op.drop_table('show')
    op.drop_table('artist_genre_items')
    op.drop_table('venue')
    op.drop_table('genre')
    op.drop_table('artist')
    # ### end Alembic commands ###
